name: music-information-retrieval
channels:
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py27_0
- audioread=2.1.4=py27_1
- backports=1.0=py27_1
- backports.functools_lru_cache=1.5=py27_0
- backports.shutil_get_terminal_size=1.0.0=py_3
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- bzip2=1.0.6=1
- ca-certificates=2018.1.18=0
- certifi=2016.2.28=py27_0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.2.1=py27_0
- enum34=1.1.6=py27_1
- ffmpeg=3.4.2=0
- freetype=2.8.1=0
- funcsigs=1.0.2=py_2
- functools32=3.2.3.2=py27_2
- futures=3.2.0=py27_0
- gettext=0.19.8.1=0
- gmp=6.1.2=0
- gnutls=3.5.17=0
- html5lib=0.9999999=py27_0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- jinja2=2.9.6=py27_0
- joblib=0.11=py27_0
- jsonschema=2.6.0=py27_0
- jupyter_client=5.1.0=py27_0
- jupyter_console=5.2.0=py27_0
- jupyter_core=4.3.0=py27_0
- kiwisolver=1.0.1=py27_1
- libiconv=1.15=0
- libidn11=1.33=0
- libpng=1.6.34=0
- librosa=0.6.0=py27_0
- markupsafe=1.0=py27_0
- matplotlib=2.2.2=py27_1
- mistune=0.7.4=py27_0
- nbformat=4.4.0=py27_0
- nettle=3.3=0
- notebook=5.0.0=py27_0
- openssl=1.0.2l=0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.7.2=py_0
- pytz=2018.3=py_0
- qtconsole=4.3.1=py27_0
- resampy=0.2.0=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.11.0=py27_1
- sqlite=3.13.0=0
- subprocess32=3.2.7=py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- tornado=5.0.1=py27_1
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=3.0.2=py27_0
- x264=20131217=3
- zlib=1.2.11=0
- entrypoints=0.2.3=py27_0
- get_terminal_size=1.0.0=py27_0
- icu=54.1=0
- jupyter=1.0.0=py27_3
- llvmlite=0.20.0=py27_0
- mkl=2017.0.3=0
- nbconvert=5.2.1=py27_0
- numba=0.35.0=np113py27_0
- numpy=1.13.1=py27_0
- pandas=0.20.3=py27_0
- pandocfilters=1.4.2=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=2
- readline=6.2=2
- scandir=1.5=py27_0
- scikit-learn=0.18.2=np113py27_0
- scipy=0.19.1=np113py27_0
- setuptools=36.4.0=py27_1
- simplegeneric=0.8.1=py27_1
- tk=8.5.18=0
- pip:
  - backports-abc==0.5
  - backports.functools-lru-cache==1.5
  - backports.shutil-get-terminal-size==1.0.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.15
prefix: /Users/daehwang/Development/anaconda/envs/music-information-retrieval

